### ISSUE TITLE
關於第二個選項的錯誤。

### ISSUE THREAD

**Issue by ABB00717** [viiccwen/GPA-calculator#1]
BUG觸發步驟:
1. 將原先的第一個選項刪除
2. 自行新增新的選項
3. 填完第一個選項，會自動跳出第二個選項
4. 在第二個選項填入的任何學分以及等第都不會納入計算

影片展示:
https://youtu.be/Xt9JNDv_sZw

**Comment by viiccwen** [comment]
**已解決**

這是由於錯誤引用科目陣列index而導致的bug及crash
目前已更新版本
感謝你的發現，謝謝！
